platform :ios, '11.0'
use_frameworks!

project 'RxCam.xcodeproj'
workspace 'RxCam'

target 'RxCam_Example' do

  pod 'RxCam', :path => '../'

  target 'RxCam_Tests' do
    inherit! :search_paths

    pod 'Quick',  '1.2.0'
    pod 'Nimble', '7.0.2'
  end
end
