platform :ios, '11.0'
use_frameworks!

project 'RxCam.xcodeproj'
workspace 'RxCam'

target 'RxCam_Example' do

  pod 'RxCam', :path => '../'

  target 'RxCam_Tests' do
    inherit! :search_paths

    pod 'Quick',       '1.2.0'
    pod 'Nimble',      '7.0.2'

    pod 'RxSwift',     '4.1.2'
    pod 'RxCocoa',     '4.1.2'
    pod 'RxSwiftExt',  '3.1.0'
    pod 'RxGesture',   '1.2.1'
  end
end
